"""Deterministic development provider for the AI Clinical Assistant module.

This module implements :class:`DummyProvider`, a configuration-free LLM
provider used for local development and testing. It never makes an
external API call and always returns the same deterministic response.
"""

from app.report_analysis.providers.base_provider import BaseProvider
from app.risk_assessment.utils.logging_utils import get_logger

logger = get_logger(__name__)

DUMMY_PROVIDER_NAME: str = "dummy"
DUMMY_RESPONSE_TEXT: str = (
    "This is a development response generated by the DummyProvider. "
    "Replace this provider with Gemini or OpenAI in production."
)


class DummyProvider(BaseProvider):
    """A deterministic, configuration-free LLM provider for development.

    ``DummyProvider`` never calls an external API, never reads
    environment variables, and never requires any configuration. It
    always returns the same fixed response, making it suitable for
    local development, tests, and environments where no real LLM
    provider is configured.
    """

    def __init__(self) -> None:
        """Initialize the DummyProvider.

        Requires no configuration and reads no environment variables.
        """
        logger.info("DummyProvider initialized.")

    def generate(self, prompt: str) -> str:
        """Return a fixed, deterministic development response.

        Args:
            prompt: The complete prompt text. Validated but otherwise
                unused, since this provider never calls an external
                model.

        Returns:
            str: A fixed, deterministic development response.

        Raises:
            InvalidUserInputError: If ``prompt`` is ``None``, empty, or
                whitespace-only.
        """
        self.validate_prompt(prompt)
        logger.info("DummyProvider generating a deterministic development response.")
        return DUMMY_RESPONSE_TEXT

    def provider_name(self) -> str:
        """Return the canonical name of this provider.

        Returns:
            str: ``"dummy"``.
        """
        return DUMMY_PROVIDER_NAME

    def is_available(self) -> bool:
        """Check whether this provider is currently usable.

        Returns:
            bool: Always ``True``, since ``DummyProvider`` requires no
            configuration or external connectivity.
        """
        return True